services:
  owldns:
    build:
      context: ..
      dockerfile: ./owl_dns/Dockerfile
      args:
        CONCURRENCY: 2
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_ADDRESS=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5